apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::113151489485:role/eksctl-securra-addon-iamserviceaccount-kube-Role1-126QSIR5G8TIM
  labels:
    name: kubernetes-external-secrets
