apiVersion: v1
kind: Service
metadata:
  name: external-secrets
  labels:
    name: kubernetes-external-secrets
spec:
  selector:
    name: kubernetes-external-secrets
  ports:
    - protocol: TCP
      port: 3001
      name: prometheus
      targetPort: prometheus
