apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- deployment.yaml
- api-service.yaml
- api-virtual-service.yaml
- securra-backend-gateway-cert.yaml
- securra-backend-gateway.yaml
