apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oauth2-proxy
  namespace: argocd
spec:
  project: default
  source:
    chart: oauth2-proxy
    helm:
      # Possible Configuration Keys - https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/overview/
      parameters:
      - name: image.repository
        value: quay.io/oauth2-proxy/oauth2-proxy
      - name: image.tag
        value: v7.1.3
      - name: configSecret.create
        value: "false"
      - name: config.existingSecret
        value: oauth2-proxy
      - name: service.port
        value: "4180"
      - name: extraArgs.provider
        value: oidc
      - name: extraArgs.set-xauthrequest
        value: "true"
      - name: extraArgs.cookie-secure
        value: "true"
      - name: extraArgs.cookie-samesite
        value: lax
      - name: extraArgs.cookie-refresh
        value: 1h
      - name: extraArgs.cookie-expire
        value: 4h
      - name: extraArgs.cookie-name
        value: _oauth2_proxy
      - name: extraArgs.email-domain
        value: "*"
      - name: extraArgs.upstream
        value: "static://200"
      - name: extraArgs.skip-auth-preflight
        value: "true"
      - name: extraArgs.skip-provider-button
        value: "true"
      - name: extraArgs.cookie-domain
        value: .securra.beyond.ai
      - name: extraArgs.whitelist-domain
        value: .securra.beyond.ai
      - name: extraArgs.oidc-issuer-url
        value: https://cognito-idp.us-west-2.amazonaws.com/us-west-2_5BWzu3lFw
      # - name: extraArgs.login-url
      #   value: "https://auth.https://cognito-idp.us-west-2.amazonaws.com/us-west-2_5BWzu3lFw/auth/realms/kubeflow/protocol/openid-connect/auth"
      # - name: extraArgs.oidc-jwks-url
      #   value: "https://https://cognito-idp.us-west-2.amazonaws.com/us-west-2_5BWzu3lFw/keys"
      # - name: extraArgs.redeem-url
      #   value: "https://auth.https://cognito-idp.us-west-2.amazonaws.com/us-west-2_5BWzu3lFw/auth/realms/kubeflow/protocol/openid-connect/token"
      # - name: extraArgs.profile-url
      #   value: "https://auth.https://cognito-idp.us-west-2.amazonaws.com/us-west-2_5BWzu3lFw/auth/realms/kubeflow/protocol/openid-connect/userinfo"
      # - name: extraArgs.validate-url
      #   value: "https://auth.https://cognito-idp.us-west-2.amazonaws.com/us-west-2_5BWzu3lFw.nl/auth/realms/kubeflow/protocol/openid-connect/userinfo"
      # - name: extraArgs.scope
      #   value: email
      # - name: extraArgs.scope
      #   value: profile
      # - name: extraArgs.scope
      #   value: openid
      # - name: extraArgs.skip-oidc-discovery
      #   value: "true"
      - name: extraArgs.insecure-oidc-allow-unverified-email
        value: "true"
      - name: extraArgs.session-store-type
        value: "redis"
      - name: extraArgs.redis-connection-url
        value: redis://securra.nzlitf.ng.0001.usw2.cache.amazonaws.com:6379
    repoURL: https://oauth2-proxy.github.io/manifests
    targetRevision: 3.3.2
  destination:
    namespace: auth
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
