apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: gateways-issuer
spec:  
  selfSigned:
    $patch: delete
  acme:
    # ACME Server options:
      # https://acme-v02.api.letsencrypt.org/directory - Used to generate valid cert, but has rate limits, use for prod
      # https://acme-staging-v02.api.letsencrypt.org/directory - Used to generate dev cert without rate limits when deploying a lot
    server: https://acme-v02.api.letsencrypt.org/directory
    email: admin@beyond.ai
    privateKeySecretRef:
      name: gateways-issuer-account-key
    solvers:
    - dns01:
        route53:
          hostedZoneID: Z00349967JA0DQFO3SJE
          region: us-west-2
          # role: arn:aws:iam::113151489485:role/eksctl-securra-addon-iamserviceaccount-cert-Role1-5JILGCGR9KHF
