apiVersion: v1
kind: ServiceAccount
metadata:
  name: cert-manager
  namespace: cert-manager
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::113151489485:role/eksctl-securra-addon-iamserviceaccount-cert-Role1-5JILGCGR9KHF
