apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: securra-backend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/paloul/securra-deployment.git
    targetRevision: securra
    path: distribution/securra-backend
    kustomize:
      version: v4.0.5
  destination:
    namespace: securra-backend
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
